env:
  es6: true
  node: true
  mocha: true
parser: "babel-eslint"
extends:
  - eslint:recommended
  - plugin:flowtype/recommended
rules:
  no-warning-comments:
    - 1
    - { "terms": ["todo", "fixme"], "location": "anywhere" }
  brace-style: [1, '1tbs']
parserOptions:
  ecmaVersion: 6
  sourceType: "module"
  ecmaFeatures:
    classes: true
    experimentalObjectRestSpread : true
plugins:
  - flowtype
