---
envs:
  - browser
  - mocha
extends:
  - "eslint:recommended"
ignorePattern:
  - "**/*.min.*"
  - "vendor/*"
  - "**/node_modules/*"
  - "**/bower_components/*"
  - "frontend/webpack/*" # irelevant issues
  - "plugins/versionpress/admin/public/js/jquery.webui-popover.min.js" # 3rd party
rules:
  brace-style:
    - warn
    - 1tbs
  camelcase: warn
  comma-dangle:
    - warn
    - always-multiline
  comma-style:
    - error
    - last
  complexity: error
  curly: warn
  eol-last:
    - error
    - always
  id-length: error
  max-lines: error
  max-params:
    - error
    - 4
  no-duplicate-imports: error
  no-eq-null: error
  no-eval: error
  no-implied-eval: error
  no-invalid-this: error
  no-shadow: error
  no-undefined: error
  no-warning-comments:
    - warn
    - location: anywhere
      terms:
        - todo
        - fixme
  prefer-promise-reject-errors: error
  semi: error
